# Generated by Django 4.1.7 on 2023-03-23 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mobile',
        ),
    ]
